# Autogenerated wrapper script for FSPS_jll for x86_64-linux-gnu-libgfortran3
export fsps

using sed_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("FSPS")
JLLWrappers.@declare_library_product(fsps, "fsps.so")
function __init__()
    JLLWrappers.@generate_init_header(sed_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        fsps,
        "lib/fsps.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
